version: "3.9"

services:
  BE-Library:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BE-Library
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./BE-Library:/usr/src/app
